### PR TITLE
[chore] fix links on README

### PR DESCRIPTION
**Pull request by enriquegh**

### CODE REVIEW

**Comment by nadvolod** [comment]
@enriquegh looks like there are some conflicts bud, if you could please resolve?

**Comment by nadvolod** [comment]
@enriquegh looks like there are some conflicts bud, if you could please resolve?

**Comment by enriquegh** [comment]
Looks like you resolved them and merged?
Let me know if there's anything I can help with!

**Comment by nadvolod** [comment]
@enriquegh so weird! I did see Github acting up yesterday... Anyways. Appreciate your help. Keep it coming 👍

**Pull request merged**
